/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.Group3.foodorderingsystem.Module.Platform.Admin.Account;

import com.Group3.foodorderingsystem.Core.Util.Colors;
import com.Group3.foodorderingsystem.Module.Common.Register.model.RegisterViewModel;
import com.Group3.foodorderingsystem.Module.Platform.Admin.AdminViewModel;

public class AccountManagementPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminUserManagement
     */
    public AccountManagementPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accountRegistrationButton = new javax.swing.JButton();

        setBackground(Colors.blue_1);

        accountRegistrationButton.setText("New Account Registration");
        accountRegistrationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountRegistrationButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(accountRegistrationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(accountRegistrationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(320, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void accountRegistrationButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_accountRegistrationButtonActionPerformed
        AdminViewModel.instance.initAccountRegistration();
        AdminViewModel.instance.refresh(AdminViewModel.instance.accountRegistrationPanel);
    }// GEN-LAST:event_accountRegistrationButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accountRegistrationButton;
    // End of variables declaration//GEN-END:variables
}
