/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.Group3.foodorderingsystem.Module.Platform.Admin;

import com.Group3.foodorderingsystem.Core.Util.Colors;
import com.Group3.foodorderingsystem.Core.Util.WidgetUtil;
import com.Group3.foodorderingsystem.Core.Widget.Header;
import java.awt.Component;

/**
 *
 * @author limwe
 */
public class AdminMainFrame extends javax.swing.JFrame {

        /**
         * Creates new form AdminMainFrame
         */
        public AdminMainFrame() {
                initComponents();
                setResizable(false);
                colorInitializer();

                header.setViewportView(new Header());
                header = WidgetUtil.toEmptyPane(header);

                footer.setViewportView(AdminViewModel.instance.adminNavigator);
                footer = WidgetUtil.toEmptyPane(footer);

                panelController();
                
        }

        private void colorInitializer() {
                backgroundPanel.setBackground(Colors.blue_1);
        }

        public void panelController() {
                switch (AdminViewModel.instance.adminPanel) {
                        case SETTINGS:
                                mainPanel.setViewportView(AdminViewModel.instance.settingsPanel);
                                break;
                        case ACCOUNT_MANAGEMENT:
                                mainPanel.setViewportView(AdminViewModel.instance.newFeaturePanel);               
                                break;
                        default:
                                break;
                }

                mainPanel = WidgetUtil.toEmptyPane(mainPanel);
        }

        public void panelController(Component panel) {
                mainPanel.setViewportView(panel);
                mainPanel = WidgetUtil.toEmptyPane(mainPanel);
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        header = new javax.swing.JScrollPane();
        footer = new javax.swing.JScrollPane();
        mainPanel = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroundPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
            .addComponent(footer)
            .addComponent(mainPanel)
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(footer, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JScrollPane footer;
    private javax.swing.JScrollPane header;
    private javax.swing.JScrollPane mainPanel;
    // End of variables declaration//GEN-END:variables
}
