/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.Group3.foodorderingsystem.Module.Platform.Admin.Account.Register;

import com.Group3.foodorderingsystem.Core.Util.Colors;
import com.Group3.foodorderingsystem.Core.Util.Images;
import com.Group3.foodorderingsystem.Core.Util.WidgetUtil;
import com.Group3.foodorderingsystem.Module.Common.Register.model.RegisterViewModel;
import com.Group3.foodorderingsystem.Module.Common.Register.widget.ProgressBarPanel;
import com.Group3.foodorderingsystem.Module.Platform.Admin.AdminViewModel;

/**
 *
 * @author limwe
 */
public class AccountRegistration extends javax.swing.JPanel {

    /**
     * Creates new form AccountRegistration
     */
    public AccountRegistration() {
        initComponents();
        roleController();
        
    }

    private void roleController() {
        rightIcon.setBorder(null);
        leftIcon.setBorder(null);
        rolePicture.setBorder(null);

        rightIcon.setIcon(Images.getImage("right_arrow.png", 40, 40));
        leftIcon.setIcon(Images.getImage("left_arrow.png", 40, 40));

        rolePicture.setText("");

        rolePicture.setIcon(Images.getImage(AdminViewModel.instance.registerViewModel.getSelectedRole().imagePath, 234, 234));
        roleField.setText(AdminViewModel.instance.registerViewModel.getSelectedRole().roleName.toString());
        descriptionField.setText("<html>" + AdminViewModel.instance.registerViewModel.getSelectedRole().description + "</html>");

        progressionPanel.setViewportView(new ProgressBarPanel(1, 
                AdminViewModel.instance.registerViewModel.getSelectedRole().maxVal));
        progressionPanel = WidgetUtil.toEmptyPane(progressionPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftIcon = new javax.swing.JLabel();
        progressionPanel = new javax.swing.JScrollPane();
        rolePicture = new javax.swing.JLabel();
        rightIcon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        roleField = new javax.swing.JLabel();
        descriptionField = new javax.swing.JLabel();
        nextButton = new javax.swing.JButton();

        setBackground(Colors.blue_1);

        leftIcon.setText("leftIcon");
        leftIcon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        leftIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        leftIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leftIconMouseClicked(evt);
            }
        });

        rolePicture.setText("picture");
        rolePicture.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        rightIcon.setText("rightIcon");
        rightIcon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rightIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rightIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rightIconMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setText("You have Selected:");

        roleField.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        roleField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roleField.setText("ROLE");

        descriptionField.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        descriptionField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descriptionField.setText("description");
        descriptionField.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        nextButton.setText("Next");
        nextButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(progressionPanel)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(leftIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(roleField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rolePicture, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                                .addGap(54, 54, 54)
                                .addComponent(rightIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(progressionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(leftIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(rightIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rolePicture, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roleField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void leftIconMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_leftIconMouseClicked
        AdminViewModel.instance.registerViewModel.reorderRoles(-1);
        roleController();
    }// GEN-LAST:event_leftIconMouseClicked

    private void rightIconMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_rightIconMouseClicked
        AdminViewModel.instance.registerViewModel.reorderRoles(1);
        roleController();
    }// GEN-LAST:event_rightIconMouseClicked

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_nextButtonActionPerformed
        AdminViewModel.instance.registerViewModel.basicInfoPanel.titleInitializer();
        AdminViewModel.instance.refresh(AdminViewModel.instance.registerViewModel.basicInfoPanel);
    }// GEN-LAST:event_nextButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel descriptionField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel leftIcon;
    private javax.swing.JButton nextButton;
    private javax.swing.JScrollPane progressionPanel;
    private javax.swing.JLabel rightIcon;
    private javax.swing.JLabel roleField;
    private javax.swing.JLabel rolePicture;
    // End of variables declaration//GEN-END:variables
}
