/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.Group3.foodorderingsystem.Module.Platform.Admin.Account.Register.Widget;

import com.Group3.foodorderingsystem.Core.Model.Entity.User.CustomerModel;
import com.Group3.foodorderingsystem.Core.Model.Entity.User.VendorModel;
import com.Group3.foodorderingsystem.Core.Model.Enum.RoleEnum;
import com.Group3.foodorderingsystem.Core.Services.UserServices;
import com.Group3.foodorderingsystem.Core.Util.Colors;
import com.Group3.foodorderingsystem.Core.Util.Images;
import com.Group3.foodorderingsystem.Core.Util.WidgetUtil;
import com.Group3.foodorderingsystem.Module.Common.Register.model.RegisterRole;
import com.Group3.foodorderingsystem.Module.Common.Register.widget.ProgressBarPanel;
import com.Group3.foodorderingsystem.Module.Platform.Admin.AdminViewModel;

/**
 *
 * @author limwe
 */
public class BasicInfoPanel extends javax.swing.JPanel {

        /**
         * Creates new form BasicInfoPanel
         */
        public BasicInfoPanel() {
                initComponents();

                background.setBackground(Colors.blue_1);
                titleInitializer();
        }

        public void titleInitializer() {
                title.setText("<html>Role Selected <br> "
                                + AdminViewModel.instance.registerViewModel.getSelectedRole().roleName
                                + "</html>");
                backButton.setIcon(Images.getImage("left_arrow.png", 40, 40));

                progressBarPanel.setViewportView(new ProgressBarPanel(2,
                                AdminViewModel.instance.registerViewModel.getSelectedRole().maxVal));
                progressBarPanel = WidgetUtil.toEmptyPane(progressBarPanel);

                errorMessageText.setText("");
                errorMessageText.setForeground(Colors.red);
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                background = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                nameField = new javax.swing.JTextField();
                jLabel2 = new javax.swing.JLabel();
                emailField = new javax.swing.JTextField();
                jLabel3 = new javax.swing.JLabel();
                passwordField = new javax.swing.JPasswordField();
                jLabel4 = new javax.swing.JLabel();
                confirmPasswordField = new javax.swing.JPasswordField();
                progressBarPanel = new javax.swing.JScrollPane();
                backButton = new javax.swing.JLabel();
                title = new javax.swing.JLabel();
                NextButton = new javax.swing.JButton();
                errorMessageText = new javax.swing.JLabel();

                jLabel1.setText("Name");

                jLabel2.setText("Email");

                jLabel3.setText("Password");

                jLabel4.setText("Confirm Password");

                backButton.setText("back");
                backButton.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                backButtonMouseClicked(evt);
                        }
                });

                title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                title.setText("<html>The role of the user you are creating for is: <br> </html>");

                NextButton.setText("Next");
                NextButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                NextButtonActionPerformed(evt);
                        }
                });

                errorMessageText.setBackground(new java.awt.Color(255, 0, 51));
                errorMessageText.setText("ERROR MESSAGE");

                javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
                background.setLayout(backgroundLayout);
                backgroundLayout.setHorizontalGroup(
                                backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(progressBarPanel)
                                                .addGroup(backgroundLayout.createSequentialGroup()
                                                                .addGap(33, 33, 33)
                                                                .addGroup(backgroundLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(backgroundLayout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(backgroundLayout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                false)
                                                                                                                .addComponent(jLabel4)
                                                                                                                .addComponent(jLabel3)
                                                                                                                .addComponent(jLabel2)
                                                                                                                .addComponent(jLabel1)
                                                                                                                .addComponent(confirmPasswordField)
                                                                                                                .addComponent(passwordField)
                                                                                                                .addComponent(emailField)
                                                                                                                .addComponent(nameField,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                204,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addContainerGap(
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                backgroundLayout
                                                                                                                .createSequentialGroup()
                                                                                                                .addGroup(backgroundLayout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                .addComponent(errorMessageText,
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                .addComponent(NextButton,
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                backgroundLayout.createSequentialGroup()
                                                                                                                                                                .addComponent(title)
                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                                                                248,
                                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                                .addComponent(backButton,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                50,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                                                .addGap(24, 24, 24)))));
                backgroundLayout.setVerticalGroup(
                                backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout
                                                                .createSequentialGroup()
                                                                .addComponent(progressBarPanel,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                60,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addGroup(
                                                                                backgroundLayout.createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                .addComponent(title)
                                                                                                .addComponent(backButton,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                50,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(23, 23, 23)
                                                                .addComponent(jLabel1)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(nameField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(41, 41, 41)
                                                                .addComponent(jLabel2)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(emailField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(47, 47, 47)
                                                                .addComponent(jLabel3)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(passwordField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(31, 31, 31)
                                                                .addComponent(jLabel4)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(confirmPasswordField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                21,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(errorMessageText)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(NextButton,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                53,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(17, 17, 17)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        }// </editor-fold>//GEN-END:initComponents

        private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_backButtonMouseClicked
                AdminViewModel.navigate(
                                AdminViewModel.instance.accountRegistrationPanel);
        }// GEN-LAST:event_backButtonMouseClicked

        private void NextButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_NextButtonActionPerformed
                if (nameField == null || nameField.getText().equals("")) {
                        errorMessageText.setText("Name cannot be empty");
                        return;
                }

                if (emailField == null || emailField.getText().equals("")) {
                        errorMessageText.setText("Email cannot be empty");
                        return;
                }

                if (passwordField == null || passwordField.getPassword().length == 0) {
                        errorMessageText.setText("Password cannot be empty");
                        return;
                }

                if (confirmPasswordField == null || confirmPasswordField.getPassword().length == 0) {
                        errorMessageText.setText("Confirm Password cannot be empty");
                        return;
                }

                if (!new String(passwordField.getPassword()).equals(new String(confirmPasswordField.getPassword()))) {
                        errorMessageText.setText("Password and Confirm Password do not match");
                        return;
                }

                if (UserServices.isEmailExist(emailField.getText()) != null) {
                        errorMessageText.setText("Email already exist");
                        return;
                }

                switch (AdminViewModel.instance.registerViewModel.getSelectedRole().roleName) {
                        case CUSTOMER:
                                CustomerModel savedCustomer = new CustomerModel();
                                savedCustomer.setName(nameField.getText());
                                savedCustomer.setEmail(emailField.getText());
                                savedCustomer.setPassword(new String(passwordField
                                                .getPassword()));
                                savedCustomer.setRole(RoleEnum.CUSTOMER);
                                AdminViewModel.instance.customerRegistration = new CustomerRegistration(savedCustomer);
                                AdminViewModel.navigate(AdminViewModel.instance.customerRegistration);
                                break;
                        case VENDOR:
                                VendorModel savedVendor = new VendorModel();
                                savedVendor.setName(nameField.getText());
                                savedVendor.setEmail(emailField.getText());
                                savedVendor.setPassword(new String(passwordField
                                                .getPassword()));
                                savedVendor.setRole(RoleEnum.VENDOR);
                                AdminViewModel.instance.vendorRegistration = new VendorRegistration(savedVendor);
                                AdminViewModel.navigate(AdminViewModel.instance.vendorRegistration);
                                break;
                        default:
                                break;
                }

        }// GEN-LAST:event_NextButtonActionPerformed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton NextButton;
        private javax.swing.JLabel backButton;
        private javax.swing.JPanel background;
        private javax.swing.JPasswordField confirmPasswordField;
        private javax.swing.JTextField emailField;
        private javax.swing.JLabel errorMessageText;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JTextField nameField;
        private javax.swing.JPasswordField passwordField;
        private javax.swing.JScrollPane progressBarPanel;
        private javax.swing.JLabel title;
        // End of variables declaration//GEN-END:variables
}
