/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.Group3.foodorderingsystem.Module.Platform.Admin.Account.Register.Widget;

import com.Group3.foodorderingsystem.Core.Model.Entity.User.VendorModel;
import com.Group3.foodorderingsystem.Core.Util.Colors;
import com.Group3.foodorderingsystem.Core.Util.WidgetUtil;
import com.Group3.foodorderingsystem.Core.Widget.VendorCard;
import com.Group3.foodorderingsystem.Module.Common.Register.model.RegisterRole;
import com.Group3.foodorderingsystem.Module.Common.Register.widget.ProgressBarPanel;
import com.Group3.foodorderingsystem.Module.Platform.Admin.AdminViewModel;

public class VendorShopRegistration extends javax.swing.JPanel {

    private VendorModel vendor;

    public VendorShopRegistration(VendorModel vendor) {
        initComponents();

        refresh(vendor);
        progressBarPanel.setViewportView(new ProgressBarPanel(4, RegisterRole.Vendor.maxVal));
        progressBarPanel = WidgetUtil.toEmptyPane(progressBarPanel);

        shopCard.setViewportView(new VendorCard(
                this.vendor));
        shopCard = WidgetUtil.toEmptyPane(shopCard);

        inputFieldPanel.setViewportView(AdminViewModel.instance.vendorShopRegistrationField);
        inputFieldPanel = WidgetUtil.toEmptyPane(inputFieldPanel);
    }

    public void refresh(VendorModel vendor) {
        System.out.println(vendor.getShopName());
        this.vendor = vendor;
        shopCard.setViewportView(new VendorCard(
                this.vendor));
        shopCard = WidgetUtil.toEmptyPane(shopCard);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progressBarPanel = new javax.swing.JScrollPane();
        shopCard = new javax.swing.JScrollPane();
        inputFieldPanel = new javax.swing.JScrollPane();

        setBackground(Colors.blue_1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(progressBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
            .addComponent(shopCard)
            .addComponent(inputFieldPanel, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(progressBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shopCard, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputFieldPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane inputFieldPanel;
    private javax.swing.JScrollPane progressBarPanel;
    private javax.swing.JScrollPane shopCard;
    // End of variables declaration//GEN-END:variables
}
